controller_manager:
  ros__parameters:
    update_rate: 1000
    
    arm_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

    joint_state_broadcaster:
      type: "joint_state_broadcaster/JointStateBroadcaster"

    gripper_controller:
      type: "joint_trajectory_controller/JointTrajectoryController"

arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - axis_b
      - axis_c
      - axis_d
      - axis_e
    allow_nonzero_velocity_at_trajectory_end: true
    allow_partial_joints_goal: true
    default: true

gripper_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - axis_a
    allow_nonzero_velocity_at_trajectory_end: true
    allow_partial_joints_goal: true
